opt_in_rules: # some rules are turned off by default, so you need to opt-in
- empty_string
- vertical_whitespace
- empty_parameters

disabled_rules: # rule identifiers to exclude from running
- function_parameter_count
- trailing_whitespace
- trailing_comma
- line_length
- cyclomatic_complexity
- type_body_length
